package com.orm;
// Generated 2012-3-5 8:11:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private Teacher teacher;
     private TClass TClass;
     private String name;
     private Integer attendNum;
     private Integer taskNum;
     private String remark;
     @SuppressWarnings("rawtypes")
	private Set tasks = new HashSet(0);
     @SuppressWarnings("rawtypes")
	private Set taskrecords = new HashSet(0);
     @SuppressWarnings("rawtypes")
	private Set signs = new HashSet(0);
     @SuppressWarnings("rawtypes")
	private Set scores = new HashSet(0);

    public Course() {
    }

	
    public Course(Teacher teacher, TClass TClass, String name) {
        this.teacher = teacher;
        this.TClass = TClass;
        this.name = name;
    }
    @SuppressWarnings("rawtypes")
	public Course(Teacher teacher, TClass TClass, String name, Integer attendNum, Integer taskNum, String remark, Set tasks, Set taskrecords, Set signs, Set scores) {
       this.teacher = teacher;
       this.TClass = TClass;
       this.name = name;
       this.attendNum = attendNum;
       this.taskNum = taskNum;
       this.remark = remark;
       this.tasks = tasks;
       this.taskrecords = taskrecords;
       this.signs = signs;
       this.scores = scores;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public TClass getTClass() {
        return this.TClass;
    }
    
    public void setTClass(TClass TClass) {
        this.TClass = TClass;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAttendNum() {
        return this.attendNum;
    }
    
    public void setAttendNum(Integer attendNum) {
        this.attendNum = attendNum;
    }
    public Integer getTaskNum() {
        return this.taskNum;
    }
    
    public void setTaskNum(Integer taskNum) {
        this.taskNum = taskNum;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    @SuppressWarnings("rawtypes")
	public Set getTasks() {
        return this.tasks;
    }
    
    @SuppressWarnings("rawtypes")
	public void setTasks(Set tasks) {
        this.tasks = tasks;
    }
    @SuppressWarnings("rawtypes")
	public Set getTaskrecords() {
        return this.taskrecords;
    }
    
    public void setTaskrecords(@SuppressWarnings("rawtypes") Set taskrecords) {
        this.taskrecords = taskrecords;
    }
    @SuppressWarnings("rawtypes")
	public Set getSigns() {
        return this.signs;
    }
    
    public void setSigns(@SuppressWarnings("rawtypes") Set signs) {
        this.signs = signs;
    }
    @SuppressWarnings("rawtypes")
	public Set getScores() {
        return this.scores;
    }
    
    public void setScores(@SuppressWarnings("rawtypes") Set scores) {
        this.scores = scores;
    }




}


