package com.orm;
// Generated 2012-3-5 8:11:47 by Hibernate Tools 3.2.1.GA



/**
 * Score generated by hbm2java
 */
public class Score  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private Student student;
     private Course course;
     private Double tscore;
     private Integer stype;

    public Score() {
    }

    public Score(Student student, Course course, Double tscore, Integer stype) {
       this.student = student;
       this.course = course;
       this.tscore = tscore;
       this.stype = stype;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Double getTscore() {
        return this.tscore;
    }
    
    public void setTscore(Double tscore) {
        this.tscore = tscore;
    }
    public Integer getStype() {
        return this.stype;
    }
    
    public void setStype(Integer stype) {
        this.stype = stype;
    }




}


