package com.orm;
// Generated 2012-3-5 8:11:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private TClass TClass;
     private String sno;
     private String password;
     private String name;
     private String sex;
     private String phone;
     @SuppressWarnings("rawtypes")
	private Set taskrecords = new HashSet(0);
     @SuppressWarnings("rawtypes")
	private Set scores = new HashSet(0);
     @SuppressWarnings("rawtypes")
	private Set signrecords = new HashSet(0);

    public Student() {
    }

	
    public Student(TClass TClass, String sno, String password) {
        this.TClass = TClass;
        this.sno = sno;
        this.password = password;
    }
    @SuppressWarnings("rawtypes")
	public Student(TClass TClass, String sno, String password, String name, String sex, String phone, Set taskrecords, Set scores, Set signrecords) {
       this.TClass = TClass;
       this.sno = sno;
       this.password = password;
       this.name = name;
       this.sex = sex;
       this.phone = phone;
       this.taskrecords = taskrecords;
       this.scores = scores;
       this.signrecords = signrecords;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TClass getTClass() {
        return this.TClass;
    }
    
    public void setTClass(TClass TClass) {
        this.TClass = TClass;
    }
    public String getSno() {
        return this.sno;
    }
    
    public void setSno(String sno) {
        this.sno = sno;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    @SuppressWarnings("rawtypes")
	public Set getTaskrecords() {
        return this.taskrecords;
    }
    
    @SuppressWarnings("rawtypes")
	public void setTaskrecords(Set taskrecords) {
        this.taskrecords = taskrecords;
    }
    @SuppressWarnings("rawtypes")
	public Set getScores() {
        return this.scores;
    }
    
    @SuppressWarnings("rawtypes")
	public void setScores(Set scores) {
        this.scores = scores;
    }
    @SuppressWarnings("rawtypes")
	public Set getSignrecords() {
        return this.signrecords;
    }
    
    @SuppressWarnings("rawtypes")
	public void setSignrecords(Set signrecords) {
        this.signrecords = signrecords;
    }




}


