package com.orm;
// Generated 2012-3-5 8:11:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private Teacher teacher;
     private Course course;
     private String name;
     private String content;
     @SuppressWarnings("rawtypes")
	private Set taskrecords = new HashSet(0);

    public Task() {
    }

	
    public Task(Teacher teacher, Course course) {
        this.teacher = teacher;
        this.course = course;
    }
    @SuppressWarnings("rawtypes")
	public Task(Teacher teacher, Course course, String name, String content, Set taskrecords) {
       this.teacher = teacher;
       this.course = course;
       this.name = name;
       this.content = content;
       this.taskrecords = taskrecords;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    @SuppressWarnings("rawtypes")
	public Set getTaskrecords() {
        return this.taskrecords;
    }
    
    @SuppressWarnings("rawtypes")
	public void setTaskrecords(Set taskrecords) {
        this.taskrecords = taskrecords;
    }




}


