package com.orm;
// Generated 2012-3-5 8:11:47 by Hibernate Tools 3.2.1.GA

/**
 * Taskrecord generated by hbm2java
 */
@SuppressWarnings("serial")
public class Taskrecord implements java.io.Serializable {

    private Integer id;
    private Student student;
    private Task task;
    private Course course;
    private String name;
    private String path;
    private String remark;
    private String uptime;
    private Boolean correct;

    public Taskrecord() {
    }

    public Taskrecord(Student student, Task task, Course course, String name, String path, String remark, String uptime, Boolean correct) {
        this.student = student;
        this.task = task;
        this.course = course;
        this.name = name;
        this.path = path;
        this.remark = remark;
        this.uptime = uptime;
        this.correct = correct;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Student getStudent() {
        return this.student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Task getTask() {
        return this.task;
    }

    public void setTask(Task task) {
        this.task = task;
    }

    public Course getCourse() {
        return this.course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getUptime() {
        return this.uptime;
    }

    public void setUptime(String uptime) {
        this.uptime = uptime;
    }

    public Boolean isCorrect() {
        return correct;
    }

    public void setCorrect(Boolean correct) {
        this.correct = correct;
    }
}
