package com.orm;
// Generated 2012-3-5 8:11:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TClass generated by hbm2java
 */
public class TClass  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private String className;
     private Integer stuNum;
     private Integer rxnf;
     @SuppressWarnings("rawtypes")
	private Set signs = new HashSet(0);
     @SuppressWarnings("rawtypes")
	private Set courses = new HashSet(0);
     @SuppressWarnings("rawtypes")
	private Set students = new HashSet(0);

    public TClass() {
    }

    @SuppressWarnings("rawtypes")
	public TClass(String className, Integer stuNum, Integer rxnf, Set signs, Set courses, Set students) {
       this.className = className;
       this.stuNum = stuNum;
       this.rxnf = rxnf;
       this.signs = signs;
       this.courses = courses;
       this.students = students;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public Integer getStuNum() {
        return this.stuNum;
    }
    
    public void setStuNum(Integer stuNum) {
        this.stuNum = stuNum;
    }
    public Integer getRxnf() {
        return this.rxnf;
    }
    
    public void setRxnf(Integer rxnf) {
        this.rxnf = rxnf;
    }
    @SuppressWarnings("rawtypes")
	public Set getSigns() {
        return this.signs;
    }
    
    @SuppressWarnings("rawtypes")
	public void setSigns(Set signs) {
        this.signs = signs;
    }
    @SuppressWarnings("rawtypes")
	public Set getCourses() {
        return this.courses;
    }
    
    @SuppressWarnings("rawtypes")
	public void setCourses(Set courses) {
        this.courses = courses;
    }
    @SuppressWarnings("rawtypes")
	public Set getStudents() {
        return this.students;
    }
    
    @SuppressWarnings("rawtypes")
	public void setStudents(Set students) {
        this.students = students;
    }




}


