package com.orm;
// Generated 2012-3-5 8:11:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	 private Integer id;
     private String name;
     private String username;
     private String password;
     private Integer qx;
     @SuppressWarnings("rawtypes")
	private Set courses = new HashSet(0);
     @SuppressWarnings("rawtypes")
	private Set tasks = new HashSet(0);

    public Teacher() {
    }

    @SuppressWarnings("rawtypes")
	public Teacher(String name, String username, String password, Integer qx, Set courses, Set tasks) {
       this.name = name;
       this.username = username;
       this.password = password;
       this.qx = qx;
       this.courses = courses;
       this.tasks = tasks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getQx() {
        return this.qx;
    }
    
    public void setQx(Integer qx) {
        this.qx = qx;
    }
    @SuppressWarnings("rawtypes")
	public Set getCourses() {
        return this.courses;
    }
    
    @SuppressWarnings("rawtypes")
	public void setCourses(Set courses) {
        this.courses = courses;
    }
    @SuppressWarnings("rawtypes")
	public Set getTasks() {
        return this.tasks;
    }
    
    @SuppressWarnings("rawtypes")
	public void setTasks(Set tasks) {
        this.tasks = tasks;
    }




}


